// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package images

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func newQueries(db DBTX) *queries {
	return &queries{db: db}
}

type queries struct {
	db DBTX
}

func (q *queries) WithTx(tx *sql.Tx) *queries {
	return &queries{
		db: tx,
	}
}
