# docker-compose --file "dev/test-databases.docker-compose.yml" up -d

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: django-pages-test
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: django-pages-test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local