// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Nigel2392/go-django/src/contrib/admin"
import "html/template"
import "bytes"
import "net/http"
import "github.com/Nigel2392/go-django/src/contrib/pages/page_models"
import "github.com/Nigel2392/go-django/src/views/list"
import "github.com/Nigel2392/go-django/src/core/attrs"
import "github.com/Nigel2392/go-django/src"
import "github.com/Nigel2392/go-django/src/core/trans"

var (
	_ADMIN_HOMEPAGE_PAGE_COUNT int32 = 5
)

type PagesAdminHomeComponent struct {
	AdminApplication *admin.AdminApplication
	Request          *http.Request
}

func (p *PagesAdminHomeComponent) html(upper *list.List[attrs.Definer]) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"pages-admin-homepage-component\"><div class=\"pages-admin-homepage-component-title\"><h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(trans.T("Pages"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/contrib/pages/django_admin_home_component.templ`, Line: 25, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h2></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = upper.Component().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func (p *PagesAdminHomeComponent) HTML() template.HTML {
	var qs = pageApp.QuerySet()
	var pages, err = qs.AllNodes(
		p.Request.Context(),
		page_models.StatusFlagNone,
		"-updated_at",
		0, _ADMIN_HOMEPAGE_PAGE_COUNT,
	)
	if err != nil {
		return template.HTML("")
	}

	var app, ok = admin.AdminSite.Apps.Get(AdminPagesAppName)
	if !ok {
		return template.HTML("")
	}

	model, ok := app.Models.Get(AdminPagesModelPath)
	if !ok {
		return template.HTML("")
	}

	var columns = make([]list.ListColumn[attrs.Definer], len(model.ListView.Fields)+1)
	for i, field := range model.ListView.Fields {
		columns[i+1] = model.GetColumn(model.ListView, field)
	}

	columns[0] = columns[1]
	columns[1] = &admin.ListActionsColumn[attrs.Definer]{
		Actions: getListActions(p.Request, django.Reverse("admin")),
	}

	var pagesList = make([]attrs.Definer, len(pages))
	for i, page := range pages {
		pagesList[i] = &page
	}

	var listComponent = list.NewList(
		pagesList,
		columns...,
	)

	var b bytes.Buffer
	err = p.html(listComponent).Render(
		p.Request.Context(), &b,
	)
	if err != nil {
		return template.HTML("")
	}

	return template.HTML(b.String())
}

func (p *PagesAdminHomeComponent) Ordering() int {
	return 5
}

var _ = templruntime.GeneratedTemplate
