// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.mysql.sql

package models_mysql

import (
	"context"

	"github.com/Nigel2392/django/contrib/pages/models"
)

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM PageNode
WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getChildren = `-- name: GetChildren :many
SELECT id, title, path, depth, numchild, page_id, typeHash
FROM PageNode
WHERE path LIKE CONCAT(?, '%') AND depth = ? + 1
`

func (q *Queries) GetChildren(ctx context.Context, path interface{}, depth interface{}) ([]models.PageNode, error) {
	rows, err := q.db.QueryContext(ctx, getChildren, path, depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.PageNode
	for rows.Next() {
		var i models.PageNode
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Path,
			&i.Depth,
			&i.Numchild,
			&i.PageID,
			&i.Typehash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescendants = `-- name: GetDescendants :many
SELECT id, title, path, depth, numchild, page_id, typeHash
FROM PageNode
WHERE path LIKE CONCAT(?, '%') AND depth > ?
`

func (q *Queries) GetDescendants(ctx context.Context, path interface{}, depth int64) ([]models.PageNode, error) {
	rows, err := q.db.QueryContext(ctx, getDescendants, path, depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.PageNode
	for rows.Next() {
		var i models.PageNode
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Path,
			&i.Depth,
			&i.Numchild,
			&i.PageID,
			&i.Typehash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, title, path, depth, numchild, page_id, typeHash
FROM PageNode
WHERE id = ?
`

func (q *Queries) GetNodeByID(ctx context.Context, id int64) (models.PageNode, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i models.PageNode
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Path,
		&i.Depth,
		&i.Numchild,
		&i.PageID,
		&i.Typehash,
	)
	return i, err
}

const getNodeByPath = `-- name: GetNodeByPath :one
SELECT id, title, path, depth, numchild, page_id, typeHash
FROM PageNode
WHERE path = ?
`

func (q *Queries) GetNodeByPath(ctx context.Context, path string) (models.PageNode, error) {
	row := q.db.QueryRowContext(ctx, getNodeByPath, path)
	var i models.PageNode
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Path,
		&i.Depth,
		&i.Numchild,
		&i.PageID,
		&i.Typehash,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :execlastid
INSERT INTO PageNode (title, path, depth, numchild, page_id, typeHash)
VALUES (?, ?, ?, ?, ?, ?)
`

func (q *Queries) InsertNode(ctx context.Context, title string, path string, depth int64, numchild int64, pageID int64, typehash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNode,
		title,
		path,
		depth,
		numchild,
		pageID,
		typehash,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const updateNode = `-- name: UpdateNode :exec
UPDATE PageNode
SET title = ?, path = ?, depth = ?, numchild = ?, page_id = ?, typeHash = ?
WHERE id = ?
`

func (q *Queries) UpdateNode(ctx context.Context, title string, path string, depth int64, numchild int64, pageID int64, typehash string, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateNode,
		title,
		path,
		depth,
		numchild,
		pageID,
		typehash,
		iD,
	)
	return err
}

const updateNodePathAndDepth = `-- name: UpdateNodePathAndDepth :exec
UPDATE PageNode
SET path = ?, depth = ?
WHERE id = ?
`

func (q *Queries) UpdateNodePathAndDepth(ctx context.Context, path string, depth int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateNodePathAndDepth, path, depth, iD)
	return err
}
