// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package action_menu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

import "net/http"
import "github.com/Nigel2392/django/core/attrs"

type ActionMenu struct {
	Items []Item
}
