# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: (Queries) Test package
on: [pull_request, push]

jobs:
  build:
    env:
      # See contrib/admin/middleware.go for more information
      GITHUB_ACTIONS: 1

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Test SQLite queries
      run: go test -v -tags=sqlite ./queries/... --failfast

    - name: Test MySQL queries
      run: go test -v -tags=mysql_local ./queries/... --failfast