# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test race conditions in package
on: [pull_request, push]

jobs:
  build:
    env:
      # See contrib/admin/middleware.go for more information
      GITHUB_ACTIONS: 1

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Race Test
      run: go test -v --race --tags=testing_auth --tags=noracing ./...
